### PR TITLE
solved crossInACircleFilled to crossInCircleFilled

### LINKED ISSUE #1045: Rename `crossInACircleFilled` to `crossInCircleFilled`
https://opensearch.slack.com/archives/C05389T9LJC/p1695072084427309?thread_ts=1694535707.701519&cid=C05389T9LJC

The files should be renamed to not have the `A` and the icon type should be `crossInCircleFilled` but `crossInACircleFilled` should still point to `crossInCircleFilled` for backwards compatibility

### PR DESCRIPTION
**Pull request by Harshninave04**
### Description
Made changes to the file name as mentioned in issues #1045 

### Issues Resolved
Changed the file name from crossInACircleFilled to crossInCircleFilled
Fixes #1045

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by BSFishy** [comment]
Thanks for this change! There are a few remnants to finish this task off. First, we need to make sure the `icon` component will reference the correct file:

https://github.com/opensearch-project/oui/blob/a5576f380afcf9308f987060ca7005c699668584/src/components/icon/icon.tsx#L114

We also want to make sure `crossInACircleFilled` works as an icon type as well, for backwards compatibility.

Additionally, the doc site should be updated to reflect this change:

https://github.com/opensearch-project/oui/blob/a5576f380afcf9308f987060ca7005c699668584/src-docs/src/views/icon/icons.js#L74

Finally, most likely, the snapshots will need to be updated:

```
yarn test-unit icon -u
```

**Comment by Harshninave04** [comment]
I'm new to this project and I've been trying to make some changes, but I've run into a few challenges. Being a beginner, I'm having trouble making the necessary changes to the repository, and I'm also facing issues with running Yarn.

**Comment by BSFishy** [comment]
Sure, no problem. For starters, I recommend following this guide if you haven't already: https://github.com/opensearch-project/oui/blob/main/DEVELOPER_GUIDE.md#running-locally

Additionally, this work is roughly following this guide: https://github.com/opensearch-project/oui/blob/main/wiki/creating-icons.md#prepare-the-pull-request

Except instead of adding a new icon, we're renaming one.

If you're still having issues, feel free to post them here and I'd be happy to guide you through them.

**Comment by joshuarrrr** [comment]
@Harshninave04 Nice to meet you 👋 ! Sorry you're having some initial challenges, but we'll help you get through them. You may also consider joining the slack instance (https://opensearch.org/slack.html) and specifically the [#dashboards-ux](https://opensearch.slack.com/archives/C05389T9LJC) channel where most of the OUI maintainers are. If we aren't able to get your environment working via GitHub and Slack, we also have developer office hours every 2 weeks: https://forum.opensearch.org/t/opensearch-dashboards-developer-office-hours-2023-09-21/14915/2

**Comment by joshuarrrr** [comment]
@BSFishy Also had some yarn-related install notes on an issue to improve the developer guide in OpenSearch Dashboards. This repo is slightly different, but his summaries there might point you in the right direction: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5067#issuecomment-1728196966

**Comment by Harshninave04** [comment]
> @Harshninave04 Nice to meet you 👋 ! Sorry you're having some initial challenges, but we'll help you get through them. You may also consider joining the slack instance (https://opensearch.org/slack.html) and specifically the [#dashboards-ux](https://opensearch.slack.com/archives/C05389T9LJC) channel where most of the OUI maintainers are. If we aren't able to get your environment working via GitHub and Slack, we also have developer office hours every 2 weeks: https://forum.opensearch.org/t/opensearch-dashboards-developer-office-hours-2023-09-21/14915/2

Joined the slack !! Feeling apprehensive about taking the first step in a crowd of experienced ppl...☹️

**Comment by joshuarrrr** [comment]
superseded by https://github.com/opensearch-project/oui/pull/1113

**Pull request closed without merging**
