### PR TITLE
Theme (Header) - update next background

### PR DESCRIPTION
**Pull request by joshuarrrr**
### Description
Updates default header background in `next` theme (dark and light) to use the page background.

### Issues Resolved

Fixes https://github.com/opensearch-project/oui/issues/901

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] All tests pass
  - [ ] `yarn lint`
  - [ ] `yarn test-unit`
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### OUI doc site examples

Note that there is no change to existing theme behavior, screenshots provided just for reference and verification

Screenshot 2023-08-15 at 12-34-57 OpenSearch UI
Screenshot 2023-08-15 at 12-35-15 OpenSearch UI
Screenshot 2023-08-15 at 12-35-54 OpenSearch UI
Screenshot 2023-08-15 at 12-36-34 OpenSearch UI

### Examples that demonstrate how this background will appear with the defined dark header above (the default layout):
Note that there is no change to existing theme behavior, screenshots provided just for reference and verification

Screenshot 2023-08-15 at 13-30-19 Visual Consistency Dashboard - OpenSearch Dashboards
Screenshot 2023-08-15 at 13-31-09 Visual Consistency Dashboard - OpenSearch Dashboards
Screenshot 2023-08-15 at 13-38-00 Visual Consistency Dashboard - OpenSearch Dashboards
Screenshot 2023-08-15 at 13-39-48 Visual Consistency Dashboard - OpenSearch Dashboards

### CODE REVIEW

**Review by BSFishy — APPROVED** [review]

**Review by AMoo-Miki — APPROVED** [review]

**Review by SergeyMyssak — APPROVED** [review]

**Comment by joshuarrrr** [comment]
Awaiting approval from @KrooshalUX

**Comment by KrooshalUX** [comment]
The effect isn't coming through when the stacked nav is present. I would expect that the background changes for both layers of the stacked nav. Is it possible to show examples of that? Since we don't have telemetry on how many people use stacked vs condensed nav, its a little tough to make the call on the color just impacting one line of the header.

**Comment by joshuarrrr** [comment]
> The effect isn't coming through when the stacked nav is present. I would expect that the background changes for both layers of the stacked nav.

No, that's not expected, because we didn't change the colors for the "dark" variant of the nav - see https://github.com/opensearch-project/oui/issues/901#issuecomment-1644781020 and the comment below it for the actual values

> Is it possible to show examples of that?

I'm not following what you'd like to see an example of - can you provide either color values or mocks? 

> Since we don't have telemetry on how many people use stacked vs condensed nav, its a little tough to make the call on the color just impacting one line of the header.

Because the stacked nav is still the default, the vast majority of users will see it, unless they've cared enough to change the settings since it was introduced in 2.1.0. See https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1834 for options on making the condensed view more common for users.

**Comment by KrooshalUX** [comment]
@joshuarrrr Here is a mock up of both sidebar and header with the background as the same as the page color 
image

**Comment by joshuarrrr** [comment]
@KrooshalUX I've updated the change and also the screenshots, so ready for your re-review.

One note - after discussing with @AMoo-Miki and @BSFishy, we think it's important (for now) to make sure that the next light theme still respects a dark header theme. Instead, the `dark` header background will be the same as the `next` dark page background color. The reason we can't really use the next light page background color is that the `dark` header prop also sets lots of styles on the children. It would make most sense to deprecate that once we drop the current theme, drop support for the expanded header, or both.

**Comment by KrooshalUX** [comment]
+ @kgcreative for awareness on outcome.

**Comment by joshuarrrr** [comment]
@kgcreative Any additional UX concerns here based on the screenshots provided?

**Pull request merged**
