### PR TITLE
[Manual][backport 1.x] Several changes

### PR DESCRIPTION
**Pull request by AMoo-Miki**
# Do not squash for merge

### Description

fixed invalid link in FAQ.md (#751)
Delete Kibana reference in commands (#535)
Updated the content and Icons in the section CssUtilityClasses (#368)
Removed GitHub column from all the tables (#371)
Update getting_started.md to remove elastic reference and other changes (#502)
Docs site changes (#96)
Updated the text in the section ErrorBoundary (#366)
Remove Split button from OUI docs (#805) (#812)
Bump semver to 7.5.3 (#855)
Replace @elastic/datemath with @opensearch/datemath (#204)
[CCI] Update dependencies (#716)
Update affiliation of Andrey and Sergey (#794)
Updated the content in the section suggest (#347)
Updated the content in the section Messages and loading (#350)
Update Notification event page (#549)
Updated the links in the section Markdown Format (#365)
Add props and examples for the combobox (#660)
Updated the section Beta badge (#338)
Update dropzone (#651)
[CCI] Update react-window and react-virtualized-auto-sizer dependencies (#652)
Move OuiBottomBar default inline styles to the CSS file (#694)
Updated bug issue template (#764)
[OuiComboBox] Add docs for icon and revise example for clearOnBlur (#806)
Update the default branch (#798)
[CCI] Add `useDeprecatedPropWarning` and align with `deprecated` hoc (#762)
Normalize interlink URL usage (#720)
change beta to experimental (#383)
Bump @faker-js/faker to v8 (#768)
Migrate from faker to @faker-js/faker (#655)
Update @svgr/core and @svgr/plugin-svgo (#649)
Updated the section drag and drop (#514)
Updated the kibana to opensearch_dashboards (#343)
Updated the section Collapsable Nav (#330)
Update Comment List Docs (#252)
OUI combo box refine (#183)
Remove beta badge accent color (#99)

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] All tests pass
  - [ ] `yarn lint`
  - [ ] `yarn test-unit`
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by joshuarrrr — APPROVED** [review]
I reviewed all the PR titles, and they all made sense to me as backports. @AMoo-Miki How did you go about generating this list? Is it something we can automate?

**Review by andreymyssak — COMMENTED** [review]
Hi @AMoo-Miki, https://github.com/opensearch-project/oui/pull/798 is not intended for backport, as this change is purely for the master branch. If we merge it in `1.x`, then the `master` header will not be hidden on the `/package/changelog` page
https://github.com/opensearch-project/oui/blob/f8d56ba11811d600eb74de9d6b71e8ab9d16a1d8/src-docs/src/views/package/changelog.js#L17-L20
But in `1.x` we use
https://github.com/opensearch-project/oui/blob/b23ff4b7137aadc43c838d74a1903f0222967e10/CHANGELOG.md?plain=1#L2

This does not break anything for the user as it is documentation, as an option we can create a separate PR to change the default branch to `main` in the `1.x` version and be in sync with the version that is in `master`.

The rest of the PRs don't break anything.

**Comment by AMoo-Miki** [comment]
@andreymyssak, thanks for your input. I looked through #798 which replaced `master` with `main`; not having it makes `1.x` have incorrect references to `master`. The changelog pages ([1.1](https://oui.opensearch.org/1.1/#/package/changelog) and [1.2](https://oui.opensearch.org/1.2/#/package/changelog)) are directly pulled from the `CHANGELOG.md` files of those branches and all branches have broken CHANGELOG.md files that are missing any entries for their versions; we will have to clean them up separately.

**Review by ashwin-pc — APPROVED** [review]
The changeset looks good, I did notice that two failed backports are missing in this diff, did you miss them or were they intentional?

- Update changelog with 1.1 info  
    Missing backports: ["backport 1.x","backport 1.1"]  
    ID: 718 | [Verify](https://github.com/opensearch-project/oui/pulls?q=Update%20changelog%20with%201.1%20info)
- [CCI] Revert changes to chart themes  
    Missing backports: ["backport 1.x"]  
    ID: 831 | [Verify](https://github.com/opensearch-project/oui/pulls?q=%20Revert%20changes%20to%20chart%20themes)

**Review by andreymyssak — APPROVED** [review]

**Review by SergeyMyssak — APPROVED** [review]

**Comment by AMoo-Miki** [comment]
> The changeset looks good, I did notice that two failed backports are missing in this diff, did you miss them or were they intentional?
> 
>     * Update changelog with 1.1 info
>       Missing backports: ["backport 1.x","backport 1.1"]
>       ID: 718 | [Verify](https://github.com/opensearch-project/oui/pulls?q=Update%20changelog%20with%201.1%20info)
> 
>     * [CCI] Revert changes to chart themes
>       Missing backports: ["backport 1.x"]
>       ID: 831 | [Verify](https://github.com/opensearch-project/oui/pulls?q=%20Revert%20changes%20to%20chart%20themes)

Thanks. I will have to do another pass after this is merged.

**Pull request merged**
