### PR TITLE
Remove `babel-core` dep and upgrade `babel-template`

### PR DESCRIPTION
**Pull request by joshuarrrr**
### Description

Upgrade `@babel/template` to `7.10.4`. Validated that `yarn build` still works correctly.

### Issues Resolved

Fixes https://github.com/opensearch-project/oui/issues/1088

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] All tests pass
  - [ ] `yarn lint`
  - [ ] `yarn test-unit`
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by BSFishy — APPROVED** [review]

**Comment by BSFishy** [comment]
Does **not** actually fix #1088. The CVE is in `@babel/traverse`, which isn't changed in this PR

**Comment by joshuarrrr** [comment]
@BSFishy It does actually fix #1088; It removes the dependency of babel-traverse from the yarn.lock:

**Comment by BSFishy** [comment]
> @BSFishy It does actually fix #1088; It removes the dependency of babel-traverse from the yarn.lock:

That's only one of the versions of `@babel/traverse` though:

https://github.com/opensearch-project/oui/blob/ae0171d5fd0ffb9237367d2d8e351be9d4638623/yarn.lock#L1199-L1244

The CVE is only resolved in version 7.23.2

**Review by AMoo-Miki — APPROVED** [review]

**Comment by joshuarrrr** [comment]
Mend failures can be ignored, as they will be fixed in other PRs.

**Pull request merged**
