### PR TITLE
Update to Webpack 5

### LINKED ISSUE #584: Upgrade to Webpack 5
Webpack v4 is old and outdated and should be upgraded to Webpack v5. Mend already raised a PR (#545) to do this, however that PR simply upgrades the package number and doesn't actually do any migration work. It's possible that migration isn't _extremely_ necessary, however it would be good to make sure we're not using anything that's deprecated.

This issue will be somewhat a copy of the content on Webpack's migration guide with added context for some steps and with some steps removed that have already been done: https://webpack.js.org/migrate/5/

This migration should take place after #578 is merged.

When performing this migration, please make a draft PR and put each top-level step in a separate commit. This will make it easier to see what's going on while the migration is happening, catch any mistakes during the process, and diagnose issues if they arrise.

Steps:
 - [ ] Upgrade `webpack-cli` to `^5.0.1` in `package.json` and run a `yarn install`
 - [ ] Update plugins and loaders to their latest versions
    - [ ] Upgrade `babel-loader` to `^9.1.2`
    - [ ] Upgrade `style-loader` to `^3.3.1`
    - [ ] Upgrade `css-loader` to `^6.7.3`
    - [ ] Upgrade `postcss-loader` to `^7.0.2`
    - [ ] Upgrade `sass-loader` to `^13.2.0`
    - [ ] Upgrade `file-loader` to `^6.2.0`
    - [ ] Upgrade `url-loader` to `^4.1.1`
    - [ ] Upgrade `html-webpack-plugin` to `^5.5.0`
    - [ ] Upgrade `circular-dependency-plugin` to `^5.2.2`
    - [ ] Upgrade `terser-webpack-plugin` to `^5.3.7`
    - [ ] Upgrade `fork-ts-checker-webpack-plugin` to `^8.0.0`
 - [ ] Run `yarn install` then both `yarn build` and `yarn build-docs` to make sure there are no build warnings or errors
    - If there are warnings or errors in this step, consult help here
 - [ ] Set the following Webpack config options in both Webpack configs (`src/webpack.config.js` and `src-docs/webpack.config.js`):
    - [ ] `node.Buffer`: `false`
    - [ ] `node.process`: `false`
 - [ ] Run `yarn build` and `yarn build-docs` again to see if there are any errors
    - If there are warnings or errors in this step, consult help here
 - [ ] Remove the Webpack config options from the previous step (`node.Buffer` and `node.process`)
 - [ ] Upgrade `webpack` to `^5.76.0` and run `yarn install`
 - [ ] Clean up configuration
    - [ ] Replace `node.fs: 'empty'` with `resolve.fallback.fs: false` in `src-docs/webpack.config.js`
    - [ ] Follow up: replace `url-loader` and `file-loader` with Webpack asset loaders
 - [ ] Run the following commands again to see if there are any errors
    - [ ] `yarn build`
    - [ ] `yarn build-docs`
    - [ ] `yarn start`
    - [ ] `yarn test-unit`
    - [ ] `yarn lint`
    - If there are warnings or errors in this step, consult help here

If the builds succeeded in the last step, the migration is complete! Mark the PR as ready for review.

### PR DESCRIPTION
**Pull request by jmetev1**
### Description
I continued from @AbhishekReddy1127 pr to upgrade webpack. It has some import problems. I fixed them. 
 
### Issues Resolved
Fixes #584 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] All tests pass
  - [ ] `yarn lint`
  - [ ] `yarn test-unit`
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by BSFishy** [comment]
This is awesome! Thanks for finishing this up. It was killing me trying to figure out why those imports were breaking.

On a side note, we require DCO to pass, meaning you need to sign your commits (Reference: https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin). You might need to rewrite your git history to achieve this. Make sure all commits are signed off so that we can merge (Specifically, [`acc7c54`](https://github.com/opensearch-project/oui/pull/765/commits/acc7c5486a0152075903cf49a7932a08c75bb087) and [`566e3f4`](https://github.com/opensearch-project/oui/pull/765/commits/566e3f4592b5b34bddc89f5cc034a19e23da371c) need to be signed off) :)

**Comment by BSFishy** [comment]
Additionally, it looks like you also need to update the `yarn.lock` again. Running `yarn install` should fix that

**Comment by jmetev1** [comment]
yeah the problem with yarn lock is i can't yarn install due to puppeteer. My issue is discussed here: https://github.com/puppeteer/puppeteer/issues/6622 . They have a solution but i was hoping someone had a simpler way. It looks like puppeteer is only used for accessibility tests which don't appear to be run in ci so maybe i could just take it out? @BSFishy

**Comment by BSFishy** [comment]
If you'd like, I can do the final cleanup for you, once you sign the commits. I'm going through all of the commands and everything to do one last sanity test. So far, it looks like we have:
 1. Update yarn.lock
 2. Update snapshots
 3. Revert #554 to fix build
 4. ?? Other things for `yarn build-docs` or `yarn start`?

But I don't think we want to take puppeteer out. There is a PR open to enable it in CI, we just haven't gotten around to merging it #641

**Comment by BSFishy** [comment]
Alright, I've gotten all of the commands working properly. For some reason Github isn't allowing me to push to your branch, so I pushed my changes to here: https://github.com/BSFishy/oui/commit/a033f123e673181ffcb8c21e0e66de52beabfd69

If you include those changes, I'll run an integ sanity test with Dashboards and we can push this through!

**Comment by jmetev1** [comment]
ok i've pulled in your cleanup. so now you'll run ci? anything else i need to do?

**Comment by jmetev1** [comment]
also do you have any plans for addressing puppeteer problem? i assume it will just get worse as more people move to apple silicon. i think one option is jumping to playwright

**Comment by BSFishy** [comment]
> ok i've pulled in your cleanup. so now you'll run ci? anything else i need to do?

At this point in time, no. Thanks for your contribution!

Right now, I'm running an integration test with Dashboards to make sure everything works properly. So far, I've found one issue in the way the charts module is generated. I got a fix working and about to retest. I'll ping you when I'm finished with the testing. After that, we should be ready for review.

> also do you have any plans for addressing puppeteer problem? i assume it will just get worse as more people move to apple silicon. i think one option is jumping to playwright

At this point in time, not directly. We're on a team-wide modernization campaign, which will include a rewrite of OUI, which most likely will include Playwright instead of Puppeteer (or another similar tool). But as of now, since OUI v2 is on the horizon, the effort to switch to a different browser testing framework is just too much of a burden. (that is, unless a community member does it, but it's not a specific item on the roadmap).

**Comment by BSFishy** [comment]
Alright, I'm starting to loose my brain and am hoping to pass my current status off to you. It looks like these changes will be mostly compatible with Dashboards, except that the charts theme module doesn't export anything for some reason.

First off, these files:

https://github.com/opensearch-project/oui/blob/a033f123e673181ffcb8c21e0e66de52beabfd69/scripts/compile-oui.js#L314
https://github.com/opensearch-project/oui/blob/a033f123e673181ffcb8c21e0e66de52beabfd69/scripts/compile-oui.js#L337

Should be changed to look like these:

```js
    'webpack --entry-reset ./themes/charts/themes.ts --output-filename oui_charts_theme.js --output-enabled-library-types="commonjs" --config=src/webpack.config.js',
```

```js
    'webpack --entry-reset ./themes/charts/themes.ts --output-filename eui_charts_theme.js --output-enabled-library-types="commonjs" --config=src/webpack.config.js',
```

From there, the files are being generated in the correct path, but they aren't exporting anything for some reason (paths are `./dist/oui_charts_theme.js` and `./dist/eui_charts_theme.js`). I've tried playing around with some Webpack tree shaking settings to no avail. Not sure what the issue is.

**Comment by jmetev1** [comment]
i could look at that. but first what are other people doing for puppeteer? or is everyone on something besides apple silicon? @andreymyssak @AbhishekReddy1127 ?
i'm having to constantly rm puppeteer from package.json so i can do yarn install.

**Comment by jmetev1** [comment]
that compile script is intimidating. maybe you have someone else who knows more about it?

**Comment by jmetev1** [comment]
i don't think i have enough context to move forward. What was charts theme? Why was it taken out and now put back in? When was the last time it was built correctly? How can i tell if it gets output correctly? Is there a test that checks that?

**Comment by andreymyssak** [comment]
> ok sorry for tagging people. i thought puppeteer failing to install on yarn install meant the whole thing failed. but turns out everything else works fine even with that failing.

I recently ran into problems with a11y-tests, my workstation on an Apple M2, and I was getting the following error `No local server found. Expecting localhost:9999 or localhost:8080 to resolve`. I used the solution https://github.com/puppeteer/puppeteer/issues/6622#issuecomment-787912758, but with the following modifications: 

```js
browser = await puppeteer.launch({
  headless: false,
  args: ['--no-sandbox'],
  executablePath: '/opt/homebrew/bin/chromium',
});
```

```js
/*
await page.close();
await browser.close();
*/
const pages = await browser.pages();
for (let i = 0; i < pages.length; i++) {
  await pages[i].close();
}
await browser.close();
```
After that, the tests were successfully run.

**Comment by jmetev1** [comment]
good to know!

**Comment by jmetev1** [comment]
Thanks. but i should close this since there's already newer one right? https://github.com/opensearch-project/oui/pull/770

**Comment by BSFishy** [comment]
Yeah this can probably be closed. If you're still interested in helping with this, please feel free to help in that PR!

**Pull request closed without merging**
