### PR TITLE
Add docking icons

### LINKED ISSUE #1136: (OUI Icons) New - Docking states icon
**Is your feature request related to a problem? Please describe.**

For UI panels requiring screen docking regions 

**Describe the solution you'd like**

Corresponding icons for the following screen docking states - Left/Top/Right/Bottom/Takeover/Detached

Icons will represent states the user can activate for docking panels appropriately to not hinder other tasks necessary for preforming their duties. When activated, panels will dock for the convenience of uninterrupted UX - the user may chose where to dock a panel to not interfere with the flow of tasks while still remaining on screen docked in a panel of the user's desired position, possibly within a resizable container.

**Describe alternatives you've considered**

None

**Additional context**

Examples:
image

### PR DESCRIPTION
**Pull request by Hailong-am**
### Description
Add docking icons

image

image

### Issues Resolved
#1136

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by joshuarrrr** [comment]
@canascar @kgcreative Can you confirm that these are the finalized assets we want for these icons?

**Comment by kgcreative** [comment]
> @canascar @kgcreative Can you confirm that these are the finalized assets we want for these icons?

Looks good to me! @canascar, can you confirm?

**Comment by canascar** [comment]
LGTM

**Comment by Hailong-am** [comment]
@joshuarrrr seems everything looks good, can we have this merged?

**Review by BSFishy — APPROVED** [review]

**Review by ashwin-pc — APPROVED** [review]

**Pull request merged**
