### PR TITLE
Update Notification event page

### LINKED ISSUE #88: (OUI Docs) Notification event
- [ ] remove all logos from each example
- [ ] remove "beta" from page
- [ ] remove "new" from side navigation

### PR DESCRIPTION
**Pull request by manasvinibs**
### Description
 * remove all logos from each example
 * remove "beta" from page
 * remove "new" from side navigation

Screenshots: 

###  remove "new" from side navigation
 
 **Before:**  
Screenshot 2023-03-01 at 11 57 50 AM

 **After:**

Screenshot 2023-03-01 at 11 46 26 AM

###  * remove "beta" from page

**Before:**  

Screenshot 2023-03-01 at 11 59 21 AM

 **After:**

Screenshot 2023-03-01 at 11 46 14 AM

###   * remove all logos from each example

**Before:**
Screenshot 2023-03-01 at 12 14 44 PM

**After:**
  
Screenshot 2023-03-01 at 11 46 47 AM

**Before:**
Screenshot 2023-03-01 at 12 17 09 PM

**After:**

Screenshot 2023-03-01 at 11 53 04 AM

**Before:**
Screenshot 2023-03-01 at 12 18 26 PM

**After:**

Screenshot 2023-03-01 at 11 47 11 AM

**Before:**
Screenshot 2023-03-01 at 12 18 47 PM

**After:** 

Screenshot 2023-03-01 at 11 47 19 AM

### Issues Resolved
Fixes #88
 
### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by KrooshalUX** [comment]
@manasvinibs can you provide a screenshot of the changes for UX review?

**Comment by manasvinibs** [comment]
> @manasvinibs can you provide a screenshot of the changes for UX review?

I've updated the screenshots. Please take a look.

**Review by kgcreative — APPROVED** [review]
LGTM

**Comment by kgcreative** [comment]
@kroosh, should we show at least one glyph instead of a logo to show some flexibility here?

**Review by seanneumann — APPROVED** [review]
LGTM

**Review by BSFishy — APPROVED** [review]
Waiting for UX approval

**Comment by KrooshalUX** [comment]
> Waiting for UX approval

LGTM !

**Review by KrooshalUX — APPROVED** [review]
LGTM

**Pull request merged**
