### PR TITLE
replaced Elastic with OpenSearch

### PR DESCRIPTION
**Pull request by abhirajshourya**
### Description
Replaced Elastic with OpenSearch in README.md for maintaining relevance.
 
### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by seanneumann — APPROVED** [review]
:)

**Review by seanneumann — CHANGES_REQUESTED** [review]
Hi @abhirajshourya - thanks for submitting the change. Can you please add sign your request? 

https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin

**Comment by abhirajshourya** [comment]
Hi @seanneumann done! signed! :)

**Review by kavilla — APPROVED** [review]

**Review by BSFishy — APPROVED** [review]

**Comment by BSFishy** [comment]
Looks like this has been fixed on `main` already. Thanks anyway!

**Pull request closed without merging**
