### PR TITLE
[OUI Docs] Updated the logo to logoOpenSearch

### LINKED ISSUE #177: (OUI Docs) Page
Section: A full page with everything
- [x] Check the routing for the Exit Full Screen button - I a not sure if we are going to run into this issue once we move versions - it does not appear to work cross-version. (To replicate the issue, visit https://eui.elastic.co/v34.6.0/#/layout/page, click Go full screen, then click exit full screen.) 

- [ ] Update all references of logoElastic to logoOpenSearch (The logoOpenSearch has not yet been uploaded and is part of issue #248 )

### PR DESCRIPTION
**Pull request by AbhishekReddy1127**
### Description
Updated the logoElastic to LogoOpensearch in the section A full page with evreything.
Screenshot 2023-02-17 at 1 50 10 PM

 
### Issues Resolved
#177 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by BSFishy** [comment]
This might be blocked until we actually add the OpenSearch icon to OUI. Doesn't make sense having an empty icon on the doc site

**Comment by kgcreative** [comment]
For now, can we add it as a one-off SVG? I thought OUIicon allows for you to do that.

**Comment by KrooshalUX** [comment]
There is another issue where the logoOpenSearch gets replaced #248

**Comment by KrooshalUX** [comment]
@BSFishy is there a way to indicate a dependency on another issue - in order to render the correct icon the work on #248 would need to be done, unless we can proceed knowing that the update would be made.

**Comment by BSFishy** [comment]
I think dependency should just be denoted by a comment and blocked label. Just until we get the icon. I think we could just add it in a separate PR, as a one off thing like @kgcreative mentioned, but until then I don't think we should merge this one

**Comment by KrooshalUX** [comment]
#248  was updated with a url to the SVG for the logoOpenSearch, but noted about not merging this one until #248  is completed.

**Comment by KrooshalUX** [comment]
blocked by #369

**Review by seanneumann — APPROVED** [review]
👍

**Pull request merged**
