### PR TITLE
Add a11y tests to workflow

### PR DESCRIPTION
**Pull request by BSFishy**
### Description
Run accessibility tests when running the build and test workflow. The tests are and have been in the repository for a while, not sure why they weren't included in the workflow
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by BSFishy** [comment]
Accessibility errors will go away when #640 is merged

**Review by joshuarrrr — APPROVED** [review]

**Review by ashwin-pc — APPROVED** [review]

**Review by ashwin-pc — CHANGES_REQUESTED** [review]
I ddint see the test failures before i approved them, can we also fix the a11y issues before adding them to the CI? No point adding something to the CI thats broken, making the CI useless.

**Comment by BSFishy** [comment]
Converting to draft until we get guidance on how to fix a11y issues

**Comment by dblock** [comment]
Closing as unfinished. Please feel free to finish / reopen. Thanks!

[Catch All Triage w/ [1](https://github.com/dblock), [2](https://github.com/krisfreedain), [3](https://github.com/andrross)]

**Pull request closed without merging**
