### PR TITLE
Change OUI Icon page

### LINKED ISSUE #248: (OUI Docs) Icons
Section: Logos
**NOTE:** Remove indicates ONLY removing from documentation. Do NOT remove these logos from the icon set within the repo. These logos will be deprecated from the actual icon library in another issue, once investigation is done to see which ones still remain in use.
- [x] Change header to OpenSearch logos
- [x] Remove logoAppSearch
- [x] Remove logoBeats
- [x] Remove logoBusinessAnalytics
- [x] Remove logoCloud
- [x] Remove logoCloudEnterprise
- [x] Remove logoCode
- [x] Remove logoElastic
- [x] Remove logoElasticStack
- [x] Remove logoElasticsearch
- [x] Remove logoEnterpriseSearch
- [x] Remove logoKibana
- [x] Remove logoLogging
- [x] Remove logoLogstash
- [x] Remove logoMaps
- [x] Remove logoMetrics
- [x] Remove logoObservability
- [x] Remove logoSecurity
- [x] Remove logoSiteSearch
- [x] Remove logoUptime
- [x] Remove logoWorkplaceSearch

- [x] Add logoOpenSearch with https://playground.opensearch.org/ui/default_branding/opensearch_mark_default_mode.svg 

Section: Apps
Note: 
- Remove only means to remove them from documentation. Because many of these are in use as glyphs, there will need to be investigation of how many are still in use in the application, generalized and then campaigns will need to be done to implement the Glyph version vs the App Icon version. That work is tracked separately [here](https://github.com/opensearch-project/oui/issues/249)

- [x] Remove addDataApp

### PR DESCRIPTION
**Pull request by abbyhu2000**
### Description
Change icon page according to issue #248
 
### Issues Resolved
#248
Screen Shot 2023-02-21 at 2 57 43 PM

Screen Shot 2023-02-21 at 2 58 05 PM

 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] All tests pass
  - [ ] `yarn lint`
  - [ ] `yarn test-unit`
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kavilla — DISMISSED** [review]
Cool!

**Comment by kavilla** [comment]
Might need to update snapshots

**Review by KrooshalUX — APPROVED** [review]
LGTM! 

Note: I will create a follow up issue to remove some more of the app icons as it looks like my list got cut off.

**Review by ananzh — APPROVED** [review]

**Review by kavilla — APPROVED** [review]

**Review by BSFishy — APPROVED** [review]

**Comment by BSFishy** [comment]
Merging as UX has previously approved and no significant changes have been made since then

**Pull request merged**
