### PR TITLE
[OUI Docs] Removed the chart section that's using elastic charts

### LINKED ISSUE #337: (OUI Docs) Markdown plugins
Section: Putting it all together: a simple chart plugin

- [x] Remove section. This section uses EUI charts and we no longer support the use of EUI charts via OUI.

### PR DESCRIPTION
**Pull request by AbhishekReddy1127**
### Description
Removed the chart plugin section that's using elastic charts.
Screenshot 2023-02-21 at 1 39 07 PM

 
### Issues Resolved
#337 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by AbhishekReddy1127** [comment]
fixes #337

**Review by KrooshalUX — APPROVED** [review]
LGTM

**Review by kgcreative — DISMISSED** [review]
LGTM

**Review by BSFishy — APPROVED** [review]

**Review by seanneumann — APPROVED** [review]
👍

**Pull request merged**
