### PR TITLE
OUI combo box refine

### LINKED ISSUE #127: (OUI Component Refresh) Combo Box- Refine search interactions by providing a prop to allow builders to select clear or return to last valid selection
Problem defined here: #95 

Proposed solution: 
As a user is typing, it is valid to present an error state when no match is found. However, if no selection is made because no value was selected, when the focus is lost from the input box, the value should be cleared or returned to the last valid selection. Provide a prop to builders to set this interaction (clear or returned). This would change the "default" behavior, requiring the builder to prescribe NOT clearing the value after a no-match search.

### PR DESCRIPTION
**Pull request by AbhishekReddy1127**
https://user-images.githubusercontent.com/62020972/211910839-e96f020b-5bef-4fc3-9d8d-a3fd616b79ef.mov

### Description
Added the prop clearOnBlur to make the combo box input text clear when user focuses out of text box.
 
### Issues Resolved
#127 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by KrooshalUX** [comment]
@AbhishekReddy1127  Is it possible to put a demo together of the changes? I would like to interact with it before approving.

**Comment by ashwin-pc** [comment]
Love the video, very nice!

**Review by ashwin-pc — APPROVED** [review]

**Review by KrooshalUX — APPROVED** [review]
From a UX perspective via the screen-share video, this looks good to me.

**Review by seanneumann — APPROVED** [review]
👍

**Pull request merged**
