### PR TITLE
[OUI Docs] Updated the section Beacon

### LINKED ISSUE #340: (OUI Docs) Beacon
- [ ] Add `OuiCallOut` in "warning" state, at top of page with following text: "OuiBeacon should only be used in conjunction with OuiTour."

### PR DESCRIPTION
**Pull request by AbhishekReddy1127**
### Description
Updated the section Beacon.
Screenshot 2023-02-28 at 11 34 20 AM

 
### Issues Resolved
#340 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by KrooshalUX — CHANGES_REQUESTED** [review]
Nit: add space between the callout and the text "Use the OUIBeacon..."

**Review by BSFishy — DISMISSED** [review]

**Review by seanneumann — APPROVED** [review]
👍

**Comment by AbhishekReddy1127** [comment]
> Nit: add space between the callout and the text "Use the OUIBeacon..."

Updated

**Review by KrooshalUX — APPROVED** [review]
LGTM

**Review by seanneumann — APPROVED** [review]
👍

**Pull request merged**
