### PR TITLE
Updated Side nav

### LINKED ISSUE #215: (OUI Docs) Side nav
Section: Complex side nav

- [ ] Replace content in this section with the following `OuiTreeView` containing (list items represent nested content within the tree, no icons in the major sections, we will add these back when Icons have been re-created for OUI):

**OpenSearch**
Discover
Dashboard
Visualize
Stack Management
- Index Patterns
- Data Sources
- Advanced Settings
      - `<OuiIcon type="gear" />` General
      - `<OuiIcon type="accessibility" />` Accessibility
      - `<OuiIcon type="discoverApp" />` Discover
      -`<OuiIcon type="bell" />` Notifications
      - `<OuiIcon type="search" />` Search
      - `<OuiIcon type="timeline" />` Timeline
      - `<OuiIcon type="visArea" />` Visualization
- Saved Objects
 
**Observability**
Application analytics
Trace analytics
Event analytics
Metrics analytics
Operational panels
Notebooks 

Section: Nested item options
- [ ] Remove Icon next to "kibana"
- [ ] Change "Kibana" to OpenSearch Dashboards

### PR DESCRIPTION
**Pull request by AbhishekReddy1127**
### Description
Updated the content in the section side nav.

Screenshot 2023-02-15 at 1 42 57 PM

Screen Shot 2023-02-01 at 5 17 47 PM

 
### Issues Resolved
#215 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by KrooshalUX — CHANGES_REQUESTED** [review]
There is still an icon present next to "OpenSearch"

**Review by BSFishy — APPROVED** [review]

**Review by KrooshalUX — APPROVED** [review]
LGTM, thanks for making the requested changes.

**Comment by AbhishekReddy1127** [comment]
Fixed #215

**Comment by seanneumann** [comment]
Fixes #215

**Pull request merged**
