### PR TITLE
[CCI] Update faker dependency

### PR DESCRIPTION
**Pull request by andreymyssak**
### Description
Update faker dependency to 5.5.3
 
### Issues Resolved
https://github.com/opensearch-project/oui/issues/594
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [X] All tests pass
  - [X] `yarn lint`
  - [X] `yarn test-unit`
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by BSFishy** [comment]
According to https://github.com/opensearch-project/oui/issues/594#issuecomment-1479716230, `faker` is no longer supported. Why update that dependency instead of migrating to `@faker-js/faker`? Is this an intermediate step because the migration will take more effort?

**Comment by andreymyssak** [comment]
> According to [#594 (comment)](https://github.com/opensearch-project/oui/issues/594#issuecomment-1479716230), `faker` is no longer supported. Why update that dependency instead of migrating to `@faker-js/faker`? Is this an intermediate step because the migration will take more effort?

This was done intentionally, since migrating can take longer and make a lot of changes, I had in mind to do it in the new PR. What do you think, maybe we should migrate this right away?

**Comment by KrooshalUX** [comment]
Hey y'all - I would like to know if there are impacts to any component functions or interactions with this or any other migration.

**Comment by andreymyssak** [comment]
> Hey y'all - I would like to know if there are impacts to any component functions or interactions with this or any other migration.

No, it will not impact the components and their interaction, the specification of the components remains the same.

**Comment by BSFishy** [comment]
> Hey y'all - I would like to know if there are impacts to any component functions or interactions with this or any other migration.

It looks like the only place where `faker` is used is to generate realistic-looking fake data for the docsite for presentation purposes. Nothing related to component functionality or interaction. Most likely closing this in favor of #655 anyway

**Pull request closed without merging**
