### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Naurabay**
### Description
The link provided in the README file is not properly anchoring/linking to the intended section. When clicking on the link, the user does not get to the desired section, it is inactive.
 
### Issues Resolved
#569 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] All tests pass
  - [ ] `yarn lint`
  - [ ] `yarn test-unit`
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by BSFishy — APPROVED** [review]
Looks good, thanks for the contribution!

**Review by BSFishy — CHANGES_REQUESTED** [review]
Looks like DCO didn't pass. Do you think you could sign your commit? Related links:
 - https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin
 - https://www.atlassian.com/git/tutorials/rewriting-history

**Comment by joshuarrrr** [comment]
@Naurabay I see that you did sign your commit. But your github account is set to hide your email. Can you change your github settings to make your email public? Then the DCO check will pass.

**Comment by joshuarrrr** [comment]
@Naurabay we'd like to be able to merge this commit. Would you be able to set your GitHub email to be public?

**Review by joshuarrrr — APPROVED** [review]

**Review by BSFishy — APPROVED** [review]

**Pull request merged**
